export type SectionSimulation = 'mathematiques' | 'physique' | 'programmation-java';

export type EntreeSimulation = {
  description?: string;
  groupe?: string;
  misEnAvant?: boolean;
  href: string;
  icon?: string;
  statut?: 'ferme' | 'pret' | 'bientôt';
  tags?: string[];
  title: string;
};

function creerEntreesBientot(
  section: SectionSimulation,
  prefixe: string,
  debut: number,
  nombre: number
): EntreeSimulation[] {
  return Array.from({ length: nombre }, (_, index) => {
    const numero = debut + index;

    return {
      description: 'Nouvelle simulation en préparation.',
      href: `/(tabs)/${section}/${prefixe}-${numero}`,
      icon: 'progress-question',
      statut: 'pret',
      tags: ['a-venir'],
      title: 'Bientôt',
    };
  });
}

export const CATALOGUE_SIMULATIONS: Record<SectionSimulation, EntreeSimulation[]> = {
  mathematiques: [
    {
      description: "Observe la tangente et la pente en un point.",
      misEnAvant: true,
      href: '/(tabs)/mathematiques/derivees',
      icon: 'chart-line',
      statut: 'pret',
      tags: ['calcul', 'derivees', 'fonctions'],
      title: 'Dérivées',
    },
    {
      description: "Compare l'aire et les sommes de Riemann.",
      href: '/(tabs)/mathematiques/integrales',
      icon: 'chart-bell-curve',
      statut: 'pret',
      tags: ['calcul', 'aires', 'riemann'],
      title: 'Intégrales',
    },
    {
      description: 'Approche les fonctions par développement local.',
      href: '/(tabs)/mathematiques/serie-taylor',
      icon: 'chart-timeline-variant',
      statut: 'pret',
      tags: ['analyse', 'series', 'approximations'],
      title: 'Série de Taylor',
    },
    {
      description: "Explore le comportement d'une fonction aux bornes.",
      href: '/(tabs)/mathematiques/limites',
      icon: 'arrow-expand-horizontal',
      statut: 'pret',
      tags: ['analyse', 'fonctions', 'comportement'],
      title: 'Limites',
    },
    {
      description: 'Décompose un signal en fréquences simples.',
      href: '/(tabs)/mathematiques/fourier',
      icon: 'sine-wave',
      statut: 'pret',
      tags: ['analyse', 'signaux', 'trigonometrie'],
      title: 'Fourier',
    },
    {
      description: 'Lis visuellement la direction des solutions.',
      href: '/(tabs)/mathematiques/champ-de-pentes',
      icon: 'arrow-decision',
      statut: 'pret',
      tags: ['equations diff', 'analyse', 'visualisation'],
      title: 'Champ de pentes',
    },
    {
      description: 'Observe norme et direction en chaque point.',
      href: '/(tabs)/mathematiques/champ-vectoriel',
      icon: 'vector-arrange-above',
      statut: 'pret',
      tags: ['geometrie', 'vecteurs', 'visualisation'],
      title: 'Champ vectoriel',
    },
    {
      description: 'Étudie la convergence des suites de termes.',
      href: '/(tabs)/mathematiques/series',
      icon: 'sigma',
      statut: 'pret',
      tags: ['analyse', 'series', 'convergence'],
      title: 'Séries',
    },
    {
      description: 'Visualise la courbe normale et calcule une probabilite entre deux bornes.',
      href: '/(tabs)/mathematiques/loi-normale-standard',
      icon: 'chart-bell-curve',
      statut: 'pret',
      tags: ['statistiques', 'probabilites', 'distribution'],
      title: 'Loi normale standard',
    },
    {
      description: 'Compare la loi t avec la normale et explore les intervalles de confiance.',
      href: '/(tabs)/mathematiques/loi-student',
      icon: 'chart-bell-curve-cumulative',
      statut: 'pret',
      tags: ['statistiques', 'probabilites', 'distribution'],
      title: 'Loi de Student',
    },
    ...creerEntreesBientot('mathematiques', 'mathematiques', 11, 10),
  ],
  physique: [
    {
      description: 'Manipule masses et distance pour visualiser la loi de gravitation.',
      misEnAvant: true,
      href: '/(tabs)/physique/gravite',
      icon: 'orbit-variant',
      statut: 'pret',
      tags: ['mecanique', 'forces'],
      title: 'Gravite',
    },
    {
      description: "Étudie les oscillations et la période d'un pendule.",
      href: '/(tabs)/physique/pendule',
      icon: 'metronome',
      statut: 'pret',
      tags: ['mecanique', 'energie', 'oscillations'],
      title: 'Pendule',
    },
    {
      description: 'Visualise les trajectoires balistiques et les lancers obliques.',
      href: '/(tabs)/physique/mouvement-projectile',
      icon: 'chart-timeline-variant',
      statut: 'pret',
      tags: ['mecanique', 'trajectoire', 'vecteurs'],
      title: 'Mouvement projectile',
    },
    {
      description: 'Lie déformation, rappel élastique et oscillations.',
      href: '/(tabs)/physique/ressort-loi-hooke',
      icon: 'source-branch',
      statut: 'pret',
      tags: ['mecanique', 'energie'],
      title: 'Ressort et loi de Hooke',
    },
    {
      description: 'Explore la rotation uniforme et les forces centripètes.',
      href: '/(tabs)/physique/mouvement-circulaire',
      icon: 'orbit-variant',
      statut: 'pret',
      tags: ['mecanique'],
      title: 'Mouvement circulaire',
    },
    {
      description: 'Représente les lignes de champ et les interactions magnétiques.',
      href: '/(tabs)/physique/champs-magnetiques',
      icon: 'magnet',
      statut: 'pret',
      tags: ['electricite'],
      title: 'Champs magnétiques',
    },
    {
      description: 'Observe les charges, vecteurs et lignes de champ électrique.',
      href: '/(tabs)/physique/champs-electriques',
      icon: 'flash-outline',
      statut: 'pret',
      tags: ['electricite'],
      title: 'Champs électriques',
    },
    {
      description: 'Visualise réflexion, réfraction et parcours lumineux.',
      href: '/(tabs)/physique/optique-refraction',
      icon: 'glasses',
      statut: 'pret',
      tags: ['ondes'],
      title: 'Optique et réfraction',
    },
    {
      description: 'Étudie les orbites et les mouvements sous attraction centrale.',
      href: '/(tabs)/physique/mecanique-orbitale',
      icon: 'earth',
      statut: 'pret',
      tags: ['mecanique'],
      title: 'Mécanique orbitale',
    },
    {
      description: 'Compare forces de contact et resistance au mouvement.',
      href: '/(tabs)/physique/frottement',
      icon: 'drag-variant',
      statut: 'pret',
      tags: ['mecanique'],
      title: 'Frottement',
    },
    {
      description: "Observe la conservation de l'énergie et de la quantité de mouvement.",
      href: '/(tabs)/physique/collisions-elastiques',
      icon: 'vector-intersection',
      statut: 'bientôt',
      tags: ['mecanique', 'energie'],
      title: 'Collisions élastiques',
    },
    ...creerEntreesBientot('physique', 'physique', 12, 9),
  ],
  'programmation-java': [
    {
      description: 'Observe les comparaisons et les échanges successifs du tri à bulles.',
      groupe: 'tri',
      href: '/(tabs)/programmation-java/tri-bulles',
      icon: 'sort',
      statut: 'pret',
      tags: ['tri'],
      title: 'Tri à bulles',
    },
    {
      description: 'Sélectionne le minimum restant et place-le progressivement au bon endroit.',
      groupe: 'tri',
      href: '/(tabs)/programmation-java/tri-selection',
      icon: 'sort-ascending',
      statut: 'pret',
      tags: ['tri'],
      title: 'Tri par sélection',
    },
    {
      description: 'Insère chaque valeur dans la partie déjà ordonnée du tableau.',
      groupe: 'tri',
      href: '/(tabs)/programmation-java/tri-insertion',
      icon: 'sort-variant',
      statut: 'pret',
      tags: ['tri'],
      title: 'Tri par insertion',
    },
    {
      description: 'Découpe le tableau, trie les morceaux, puis fusionne les résultats.',
      groupe: 'tri',
      href: '/(tabs)/programmation-java/tri-fusion',
      icon: 'source-merge',
      statut: 'pret',
      tags: ['tri'],
      title: 'Tri fusion',
    },
    {
      description: 'Choisis un pivot et partitionne les valeurs autour de lui.',
      groupe: 'tri',
      href: '/(tabs)/programmation-java/tri-rapide',
      icon: 'call-split',
      statut: 'pret',
      tags: ['tri'],
      title: 'Tri rapide',
    },
    {
      description: 'Empile et dépile les éléments selon le principe dernier entré, premier sorti.',
      groupe: 'structures-donnees',
      href: '/(tabs)/programmation-java/pile',
      icon: 'tray-full',
      statut: 'pret',
      tags: ['structures-donnees'],
      title: 'Pile - LIFO',
    },
    {
      description: 'Ajoute à la fin et retire au début selon le principe premier entré, premier sorti.',
      groupe: 'structures-donnees',
      href: '/(tabs)/programmation-java/file',
      icon: 'format-list-numbered',
      statut: 'pret',
      tags: ['structures-donnees'],
      title: 'File - FIFO',
    },
    {
      description: 'Explore les nœuds, les liens et les insertions dans une liste chaînée.',
      groupe: 'structures-donnees',
      href: '/(tabs)/programmation-java/liste-chainee',
      icon: 'link-variant',
      statut: 'pret',
      tags: ['structures-donnees'],
      title: 'Liste chaînée',
    },
    {
      description: 'Compare taille dynamique, index et opérations courantes de ArrayList.',
      groupe: 'structures-donnees',
      href: '/(tabs)/programmation-java/arraylist',
      icon: 'view-list',
      statut: 'pret',
      tags: ['structures-donnees'],
      title: 'ArrayList',
    },
    {
      description: 'Visualise les index, les cases fixes et les parcours de tableaux.',
      groupe: 'structures-donnees',
      href: '/(tabs)/programmation-java/tableaux',
      icon: 'table',
      statut: 'pret',
      tags: ['structures-donnees'],
      title: 'Tableaux',
    },
    {
      description: 'Manipule les chaînes, les caractères et leurs index en Java.',
      groupe: 'structures-donnees',
      href: '/(tabs)/programmation-java/chaines-caracteres',
      icon: 'alphabetical-variant',
      statut: 'pret',
      tags: ['structures-donnees'],
      title: 'Chaînes et caractères',
    },
    {
      description: 'Visualise les bits, les adresses et les conversions des types primitifs.',
      groupe: 'fonctionnalites-java',
      href: '/(tabs)/programmation-java/memoire',
      icon: 'memory',
      statut: 'pret',
      tags: ['fonctionnalites-java', 'types', 'memoire'],
      title: 'Mémoire',
    },
    {
      description: "Suis plusieurs fils d'exécution et leurs effets sur le même programme.",
      groupe: 'fonctionnalites-java',
      href: '/(tabs)/programmation-java/multithreading',
      icon: 'source-branch-sync',
      statut: 'pret',
      tags: ['fonctionnalites-java'],
      title: 'Multithreading',
    },
    {
      description: 'Comprends pourquoi deux clés peuvent tomber dans le même emplacement.',
      groupe: 'fonctionnalites-java',
      href: '/(tabs)/programmation-java/collisions-hachage',
      icon: 'pound',
      statut: 'bientôt',
      tags: ['fonctionnalites-java'],
      title: 'Collisions de hachage',
    },
    {
      description: 'Relie classe parent, classe enfant, héritage et redéfinition de méthodes.',
      groupe: 'fonctionnalites-java',
      href: '/(tabs)/programmation-java/heritage',
      icon: 'family-tree',
      statut: 'bientôt',
      tags: ['fonctionnalites-java'],
      title: 'Héritage',
    },
  ],
};


